routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\CaptchaServiceController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsUpdateController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomeController::class);

Route::get('/login', [AuthController::class, 'index'])->name('auth.index');
Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

Route::get('/captcha/reload', [CaptchaServiceController::class, 'reload']);

Route::middleware(['auth'])->group(function () {

  Route::resource('/news-updates', NewsUpdateController::class);

  Route::prefix('user-profile')->group(function () {
    Route::get('/', [UserProfileController::class, 'show'])->name('user-profile');
    Route::post('/change-password', [UserProfileController::class, 'change_password'])->name('change-password');
  });

});

app/Models/NewsUpdate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NewsUpdate extends Model {
  use HasFactory;

  protected $fillable = [
    'title',
    'content',
    'image_url',
    'video_url',
  ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable {
  use HasApiTokens, HasFactory, Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array<int, string>
   */
  protected $fillable = [
    'name',
    'email',
    'password',
  ];

  /**
   * The attributes that should be hidden for serialization.
   *
   * @var array<int, string>
   */
  protected $hidden = [
    'password',
    'remember_token',
  ];

  /**
   * The attributes that should be cast.
   *
   * @var array<string, string>
   */
  protected $casts = [
    'email_verified_at' => 'datetime',
  ];
}

app/Http/Controllers/CaptchaServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CaptchaServiceController extends Controller {

  public function reload() {
    return response()->json(['captcha'=> captcha_img()]);
  }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\View\View;

use App\Models\NewsUpdate;

class HomeController extends Controller {

  public function __invoke(): View {
    return view('home', [
      'news_updates' => NewsUpdate::orderByDesc('id')->get(),
    ]);
  }

}

app/Http/Controllers/NewsUpdateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\View\View;

use App\Models\NewsUpdate;

class NewsUpdateController extends Controller {

  public function index(): View {
    return view('news-update/index', [
      'news_updates' => NewsUpdate::orderByDesc('id')->get(),
    ]);
  }

  public function show(Request $request): View {
    return view('news-update/show', [
      'news_update' => NewsUpdate::find($request->news_update),
    ]);
  }

  public function create(): View {
    return view('news-update/create', []);
  }

  public function store(Request $request) {
    $request->validate([
      'title' => 'required',
      'content' => 'required',
      'image_url' => 'required',
      'video_url' => 'required',
    ]);

    NewsUpdate::create($request->post());

    return redirect('/');
  }

  public function edit(Request $request): View {
    return view('news-update/edit', [
      'news_update' => NewsUpdate::find($request->news_update),
    ]);
  }

  public function update(Request $request) {
    $request->validate([
      'title' => 'required',
      'content' => 'required',
      'image_url' => 'required',
      'video_url' => 'required',
    ]);

    NewsUpdate::find($request->news_update)->fill($request->post())->save();

    return redirect('/');
  }

}

app/Http/Controllers/UserProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\View\View;
use App\Models\User;
use Hash;

class UserProfileController extends Controller {

  public function show(): View {
    return view('user/profile', []);
  }

  public function change_password(Request $request) {
    $request->validate([
      'old_password' => 'required',
      'new_password' => 'required|confirmed',
    ]);

    if(!Hash::check($request->old_password, auth()->user()->password)) {
      return back()->with("error", "Old Password Doesn't match!");
    }

    User::whereId(auth()->user()->id)->update([
      'password' => Hash::make($request->new_password)
    ]);

    return back()->with("status", "Password changed successfully!");
  }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('pagetitle')
  <h1>Dashboard</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">Dashboard</li>
    </ol>
  </nav>
@endsection

@section('content')
  <section class="section dashboard">
    <div class="row">

      <div class="col-lg-12">

        <!-- News & Updates Traffic -->
        <div class="card">
          <div class="filter">
            <a class="btn btn btn-outline-success btn-sm" href="{{ route('news-updates.create') }}">Add New</a>
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
              <li class="dropdown-header text-start">
                <h6>Filter</h6>
              </li>

              <li><a class="dropdown-item" href="#">Today</a></li>
              <li><a class="dropdown-item" href="#">This Month</a></li>
              <li><a class="dropdown-item" href="#">This Year</a></li>
            </ul>
          </div>

          <div class="card-body pb-0">
            <h5 class="card-title">
              News &amp; Updates
              <span>| Today</span>
            </h5>

            <div class="news">
              @foreach($news_updates as $news_update)
                <div class="post-item clearfix">
                  <img src="{{ $news_update->image_url }}" alt="">
                  <div style="position: fixed;">
                    <h4><a href="{{ route('news-updates.show', $news_update->id) }}">{{ $news_update->title }}</a></h4>
                    <p>{{ $news_update->content }}</p>
                  </div>
                  <div style="float: right">
                    <a class="btn btn-sm" href="{{ route('news-updates.edit', $news_update->id) }}"><i class="bi bi-pencil-square"></i></a>
                  </div>
                </div>
              @endforeach
            </div><!-- End sidebar recent posts-->

          </div>
        </div><!-- End News & Updates -->

      </div><!-- End Right side columns -->

    </div>
  </section>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ asset("assets/img/favicon.png") }}" rel="icon">
  <link href="{{ asset("assets/img/apple-touch-icon.png") }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ asset("vendor/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/bootstrap-icons/bootstrap-icons.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/boxicons/css/boxicons.min.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/quill/quill.snow.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/quill/quill.bubble.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/remixicon/remixicon.css") }}" rel="stylesheet">
  <link href="{{ asset("vendor/simple-datatables/style.css") }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ asset("assets/css/style.css") }}" rel="stylesheet">

  <!-- jQuery CDN File -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.0
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="{{ asset("assets/img/logo.png") }}" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    @include('layouts.partials.header-nav')

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  @include('layouts.partials.sidebar')

  <main id="main" class="main">

    <div class="pagetitle">
      @yield('pagetitle')
    </div><!-- End Page Title -->

    @yield('content')

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ asset("vendor/apexcharts/apexcharts.min.js") }}"></script>
  <script src="{{ asset("vendor/bootstrap/js/bootstrap.bundle.min.js") }}"></script>
  <script src="{{ asset("vendor/chart.js/chart.min.js") }}"></script>
  <script src="{{ asset("vendor/echarts/echarts.min.js") }}"></script>
  <script src="{{ asset("vendor/quill/quill.min.js") }}"></script>
  <script src="{{ asset("vendor/simple-datatables/simple-datatables.js") }}"></script>
  <script src="{{ asset("vendor/tinymce/tinymce.min.js") }}"></script>
  <script src="{{ asset("vendor/php-email-form/validate.js") }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ asset("assets/js/main.js") }}"></script>

</body>

</html>

resources/views/layouts/partials/header-nav.blade.php
<nav class="header-nav ms-auto">
  <ul class="d-flex align-items-center">

    <li class="nav-item d-block d-lg-none">
      <a class="nav-link nav-icon search-bar-toggle " href="#">
        <i class="bi bi-search"></i>
      </a>
    </li><!-- End Search Icon-->

    @if (Auth::check())
    <li class="nav-item dropdown">

      <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
        <i class="bi bi-bell"></i>
        <span class="badge bg-primary badge-number">4</span>
      </a><!-- End Notification Icon -->

      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
        <li class="dropdown-header">
          You have 4 new notifications
          <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="notification-item">
          <i class="bi bi-exclamation-circle text-warning"></i>
          <div>
            <h4>Lorem Ipsum</h4>
            <p>Quae dolorem earum veritatis oditseno</p>
            <p>30 min. ago</p>
          </div>
        </li>

        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="notification-item">
          <i class="bi bi-x-circle text-danger"></i>
          <div>
            <h4>Atque rerum nesciunt</h4>
            <p>Quae dolorem earum veritatis oditseno</p>
            <p>1 hr. ago</p>
          </div>
        </li>

        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="notification-item">
          <i class="bi bi-check-circle text-success"></i>
          <div>
            <h4>Sit rerum fuga</h4>
            <p>Quae dolorem earum veritatis oditseno</p>
            <p>2 hrs. ago</p>
          </div>
        </li>

        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="notification-item">
          <i class="bi bi-info-circle text-primary"></i>
          <div>
            <h4>Dicta reprehenderit</h4>
            <p>Quae dolorem earum veritatis oditseno</p>
            <p>4 hrs. ago</p>
          </div>
        </li>

        <li>
          <hr class="dropdown-divider">
        </li>
        <li class="dropdown-footer">
          <a href="#">Show all notifications</a>
        </li>

      </ul><!-- End Notification Dropdown Items -->

    </li><!-- End Notification Nav -->

    <li class="nav-item dropdown">

      <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
        <i class="bi bi-chat-left-text"></i>
        <span class="badge bg-success badge-number">3</span>
      </a><!-- End Messages Icon -->

      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
        <li class="dropdown-header">
          You have 3 new messages
          <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="message-item">
          <a href="#">
            <img src="{{ asset("assets/img/messages-1.jpg") }}" alt="" class="rounded-circle">
            <div>
              <h4>Maria Hudson</h4>
              <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
              <p>4 hrs. ago</p>
            </div>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="message-item">
          <a href="#">
            <img src="{{ asset("assets/img/messages-2.jpg") }}" alt="" class="rounded-circle">
            <div>
              <h4>Anna Nelson</h4>
              <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
              <p>6 hrs. ago</p>
            </div>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="message-item">
          <a href="#">
            <img src="{{ asset("assets/img/messages-3.jpg") }}" alt="" class="rounded-circle">
            <div>
              <h4>David Muldon</h4>
              <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
              <p>8 hrs. ago</p>
            </div>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li class="dropdown-footer">
          <a href="#">Show all messages</a>
        </li>

      </ul><!-- End Messages Dropdown Items -->

    </li><!-- End Messages Nav -->

    <li class="nav-item dropdown pe-3">

      <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
        <img src="{{ asset("assets/img/profile-img.jpg") }}" alt="Profile" class="rounded-circle">
        <span class="d-none d-md-block dropdown-toggle ps-2">{{ auth()->user()->name }}</span>
      </a><!-- End Profile Iamge Icon -->

      <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
        <li class="dropdown-header">
          <h6>{{ auth()->user()->name }}</h6>
          <span>Web Designer</span>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li>
          <a class="dropdown-item d-flex align-items-center" href="{{ route('user-profile') }}">
            <i class="bi bi-person"></i>
            <span>My Profile</span>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li>
          <a class="dropdown-item d-flex align-items-center" href="{{ route('user-profile') }}">
            <i class="bi bi-gear"></i>
            <span>Account Settings</span>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li>
          <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
            <i class="bi bi-question-circle"></i>
            <span>Need Help?</span>
          </a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>

        <li>
          <a class="dropdown-item d-flex align-items-center" href="/logout">
            <i class="bi bi-box-arrow-right"></i>
            <span>Sign Out</span>
          </a>
        </li>

      </ul><!-- End Profile Dropdown Items -->
    </li><!-- End Profile Nav -->
    @endif

  </ul>
</nav><!-- End Icons Navigation -->

resources/views/news-update/create.blade.php
@extends('layouts.app')

@section('pagetitle')
  <h1></h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">News & Updates</li>
    </ol>
  </nav>
@endsection

@section('content')
  <section class="section dashboard">
    <div class="row">

      <!-- Right side columns -->
      <div class="col-lg-12">

        <!-- News & Updates Traffic -->
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Create News Update</h5>

            <!-- Vertical Form -->
            <form action="{{ route('news-updates.store') }}" class="row g-3" method="POST">
              @csrf

              <div class="row mb-3">
                <div class="col-12">
                  <label for="title" class="form-label">Title</label>
                  <input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="content" class="form-label">Content</label>
                  <input name="content" type="text" class="form-control @error('content') is-invalid @enderror" id="content">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="image_url" class="form-label">Image URL</label>
                  <input name="image_url" type="url" class="form-control @error('image_url') is-invalid @enderror" id="image_url">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="video_url" class="form-label">Video URL</label>
                  <input name="video_url" type="url" class="form-control @error('video_url') is-invalid @enderror" id="video_url">
                </div>
              </div>

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form><!-- Vertical Form -->

          </div>
        </div>

      </div><!-- End Right side columns -->

    </div>
  </section>
@endsection

resources/views/news-update/edit.blade.php
@extends('layouts.app')

@section('pagetitle')
  <h1></h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">News & Updates</li>
    </ol>
  </nav>
@endsection

@section('content')
  <section class="section dashboard">
    <div class="row">

      <!-- Right side columns -->
      <div class="col-lg-12">

        <!-- News & Updates Traffic -->
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Edit News Update</h5>

            <!-- Vertical Form -->
            <form action="{{ route('news-updates.update', $news_update->id) }}" class="row g-3" method="POST">
              @csrf
              @method('PUT')

              <div class="row mb-3">
                <div class="col-12">
                  <label for="title" class="form-label">Title</label>
                  <input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title" value="{{ $news_update->title }}">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="content" class="form-label">Content</label>
                  <input name="content" type="text" class="form-control @error('content') is-invalid @enderror" id="content" value="{{ $news_update->content }}">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="image_url" class="form-label">Image URL</label>
                  <input name="image_url" type="url" class="form-control @error('image_url') is-invalid @enderror" id="image_url" value="{{ $news_update->image_url }}">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="video_url" class="form-label">Video URL</label>
                  <input name="video_url" type="url" class="form-control @error('video_url') is-invalid @enderror" id="video_url" value="{{ $news_update->video_url }}">
                </div>
              </div>

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form><!-- Vertical Form -->

          </div>
        </div>

      </div><!-- End Right side columns -->

    </div>
  </section>
@endsection

resources/views/news-update/index.blade.php
@extends('layouts.app')

@section('pagetitle')
  <h1></h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">News & Updates</li>
    </ol>
  </nav>
@endsection

@section('content')
  <section class="section dashboard">
    <div class="row">

      <!-- Right side columns -->
      <div class="col-lg-12">

        <!-- News & Updates Traffic -->
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Edit News Update</h5>

            <!-- Vertical Form -->
            <form class="row g-3">
              <div class="row mb-3">
                <div class="col-12">
                  <label for="title" class="form-label">Title</label>
                  <input type="text" class="form-control" id="title">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="content" class="form-label">Content</label>
                  <input type="email" class="form-control" id="content">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="image_url" class="form-label">Image URL</label>
                  <input type="text" class="form-control" id="image_url">
                </div>
              </div>

              <div class="row mb-3">
                <div class="col-12">
                  <label for="video_url" class="form-label">Video URL</label>
                  <input type="password" class="form-control" id="video_url">
                </div>
              </div>

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form><!-- Vertical Form -->

          </div>
        </div>

      </div><!-- End Right side columns -->

    </div>
  </section>
@endsection

resources/views/news-update/show.blade.php
@extends('layouts.app')

@section('pagetitle')
  <h1></h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">News & Updates</li>
    </ol>
  </nav>
@endsection

@section('content')
  <section class="section dashboard">
    <div class="row">

      <div class="col-lg-12">

        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-2">
              <img src="{{ $news_update->image_url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ $news_update->title }}</h5>
                <p class="card-text">{{ $news_update->content }}</p>
								<iframe width="420" height="315"
								src="{{ $news_update->video_url }}">
								</iframe>
              </div>
            </div>
          </div>
        </div><!-- End Card with an image on left -->

      </div><!-- End Right side columns -->

    </div>
  </section>
@endsection